### ISSUE TITLE
System or user modifications to rpm path macros break the plugin

### ISSUE THREAD

**Issue by tmzullinger** [mojohaus/rpm-maven-plugin#13]
If a /etc/rpm/macros or ~/.rpmmacros adjust path macros like `_builddir`, `_rpmdir`, `_sourcedir`, `_specdir`, `_srcrpmdir`, or `_build_name_fmt`, the plugin fails as it expects the generated packages to be in the default locations.

The plugin sets `_topdir`.  It should similarly set the other path macros so that it can be sure where the packages will be created.  (Alternately, `rpm --eval` could be used to check the paths, but that's a much bigger change with dubious benefits.)

I've created a patch to set the necessary `--define` options.  I'm not familiar with the testing methods here, so if anyone could lend a hand on what I may need to do in that regard, I would appreciate it.

**Comment by dantran** [comment]
merge at https://github.com/mojohaus/rpm-maven-plugin/commit/0f280c186794bac1366d3f4598f223f375651431  Thanks
