### ISSUE TITLE
Try to setup to run integration tests on travis (CI)

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/rpm-maven-plugin#37]
It would be nice if all integration tests could be running on travis.

**Comment by dantran** [comment]
Yes, we need them :-) can travis install rpmbuild command for us

**Comment by khmarbaise** [comment]
Fixed in master with https://github.com/mojohaus/rpm-maven-plugin/commit/8c069221d6adedb3fe88130113687709c024819f

**Comment by rickard-von-essen** [comment]
:+1:
