### ISSUE TITLE
Please migrate CodeHaus pages to home page of GitHub

### ISSUE THREAD

**Issue by tonyfalabella** [mojohaus/rpm-maven-plugin#4]
Can you please migrate CodeHaus pages to home page of GitHub?
This link no longer works: http://mojo.codehaus.org/rpm-maven-plugin/
As of 5/31/2015, CodeHaus looks like it's no longer hosting projects.

**Comment by apryce** [comment]
After updating we should also update this SO question: http://stackoverflow.com/questions/30571638/where-is-maven-rpm-plugin-documentation-after-codehaus-gone

**Comment by dennisl** [comment]
We are currently migrating all infrastructure from codehaus to github, and other places. The sites are up at www.mojohaus.org and we are working on getting redirects in place.

**Comment by Batmat** [comment]
FYI, btw, just added a notice on the www.mojohaus.org to tell people about the migration going on. Because now the redirections are installed, a lot of people are gonna see this page when they look for plugin documentation (e.g. search for "versions maven plugin" and click on the first link).

**Comment by lazyval** [comment]
Almost month since last comment. Any updates on a matter? 

![download](https://cloud.githubusercontent.com/assets/235297/8408155/48b44ba0-1e76-11e5-94d1-c8ef9cf76c9d.jpeg)

**Comment by khmarbaise** [comment]
diff --git a/pom.xml b/pom.xml
index 3fada0a..ddf211a 100644
--- a/pom.xml
+++ b/pom.xml
@@ -23,7 +23,7 @@
   <description>
     Maven plugin which assembles files into an RPM package for installation on various target UNIX systems.
   </description>
-  <url>http://mojo.codehaus.org/rpm-maven-plugin/</url>
+  <url>http://www.mojohaus.org/rpm-maven-plugin/</url>
   <inceptionYear>2005</inceptionYear>
   <licenses>
     <license>
@@ -90,18 +90,14 @@
   </prerequisites>
 
   <scm>
-    <url>http://fisheye.codehaus.org/browse/mojo/tags/rpm-maven-plugin-2.1.3</url>
-    <connection>scm:svn:https://svn.codehaus.org/mojo/tags/rpm-maven-plugin-2.1.3</connection>
-    <developerConnection>scm:svn:https://svn.codehaus.org/mojo/tags/rpm-maven-plugin-2.1.3</developerConnection>
+    <url>https://github.com/mojohaus/rpm-maven-plugin/</url>
+    <connection>scm:git:https://github.com/mojohaus/rpm-maven-plugin.git</connection>
+    <developerConnection>scm:git:https://github.com/mojohaus/rpm-maven-plugin.git</developerConnection>
   </scm>
   <issueManagement>
-    <system>jira</system>
-    <url>http://jira.codehaus.org/browse/MRPM</url>
+    <system>GitHub</system>
+    <url>https://github.com/mojohaus/rpm-maven-plugin/issues</url>
   </issueManagement>
-  <ciManagement>
-    <system>Bamboo</system>
-    <url>http://bamboo.ci.codehaus.org/browse/MOJO-MRPM</url>
-  </ciManagement>
 
   <properties>
     <mavenVersion>2.2.1</mavenVersion>
@@ -200,6 +196,22 @@
     </plugins>
   </build>
 
+  <reporting>
+    <plugins>
+    <plugin>
+      <groupId>org.apache.maven.plugins</groupId>
+      <artifactId>maven-pmd-plugin</artifactId>
+      <version>3.2</version>
+      <configuration>
+        <rulesets>
+          <ruleset>${project.basedir}/mojo_rules.xml
+          </ruleset>
+        </rulesets>
+      </configuration>
+    </plugin>
+  </plugins>
+  </reporting>
+
   <profiles>
     <profile>
       <id>run-its</id>

**Comment by khmarbaise** [comment]
So website is back online.

**Comment by lazyval** [comment]
Indeed, [site is up and running](http://www.mojohaus.org/rpm-maven-plugin/). Thanks a lot!

**Comment by dantran** [comment]
Thanks Karl.

-D

**Comment by dantran** [comment]
fixed
