### ISSUE TITLE
rpm for parameter preremoveScriptlet

### ISSUE THREAD

**Issue by ml007r** [mojohaus/rpm-maven-plugin#54]
Hi,

i am getting an exception:

[ERROR] Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.1.4:rpm (generate-rpm) on project tifserver: Unable to parse configuration of mojo org.codehaus.mojo:rpm-maven-plugin:2.1.4:rpm for parameter preremoveScriptlet: Cannot find default setter in class org.codehaus.mojo.rpm.Scriptlet -> [Help 1]

I tried to use "<preremoveScriptlet>" but its not working with version 2.1.3 / 2.1.4 & 2.1.5.
Pls advise what to do or if this is a known error...

Best regards

Marcel

**Comment by rickard-von-essen** [comment]
I assume you have a `<preremoveScript>` section. Could you share relevant parts of your pom file.

**Comment by rickard-von-essen** [comment]
You are most likely missing `<script>` or `<scriptFile>`.

**Comment by ml007r** [comment]
Yeah - you are right. we will try that!
A typicall PEBKAC-problem...

Thanks!

**Comment by ml007r** [comment]
Its working - Thanks a lot!

**Comment by Nicksxs** [comment]
@rickard-von-essen i'm building ambari then face this problem, can you help me solve this problem
