### ISSUE TITLE
Possibility to rename artifacts much like in maven-assembly

### ISSUE THREAD

**Issue by rbjorklin** [mojohaus/rpm-maven-plugin#64]
It would be nice to be able to rename artifacts like how its done in the maven-assembly-plugin. Example:

    <dependencySet>
            <outputDirectory>app</outputDirectory>
            <outputFileNameMapping>${artifact.classifier}.jar</outputFileNameMapping>
    </dependencySet>

EDIT: Might be of use: [Which properties can be used in the outputFileNameMapping parameter.](https://maven.apache.org/plugins/maven-assembly-plugin/faq.html#outputFileNameMapping)

**Comment by dantran** [comment]
see my comment in  #65
