### ISSUE TITLE
More fine grained include & exclude filters like in maven-assembly

### ISSUE THREAD

**Issue by rbjorklin** [mojohaus/rpm-maven-plugin#65]
maven-assembly has the possibility to filter on a more fine grained level which would be nice. See [Advanced Artifact-Matching in includes and excludes](http://maven.apache.org/plugins/maven-assembly-plugin/advanced-descriptor-topics.html#Advanced_Artifact-Matching_in_includes_and_excludes)

    <dependencySet>
            <outputDirectory>app</outputDirectory>
            <includes>
                <include>*:application:jar:start:*</include>
                <include>*:application:jar:stop:*</include>
            </includes>
    </dependencySet>

**Comment by dantran** [comment]
I strongly recommend for any build to populate a staging directory using other the pluginsand have rpm-m-p to convert the staging to RPM

otherwise, this plugin will become other plugins which will be extremely hard to maintain

**Comment by rbjorklin** [comment]
Brilliant, now I feel stupid for not realizing this. Thanks!
