### ISSUE TITLE
<filemode> affects directories

### ISSUE THREAD

**Issue by TomyLobo** [mojohaus/rpm-maven-plugin#8]
````xml
<mapping>
    <directory>/etc/init.d</directory>
    <username>root</username>
    <groupname>root</groupname>
    <filemode>700</filemode>
    <sources>
        <source>
            <location>${project.basedir}/src/rpm/data/etc/init.d</location>
        </source>
    </sources>
</mapping>
````

2.1-alpha-2 behaviour: /etc/init.d/myservice has 700 permissions, /etc/init.d has 700 permissions
Expected behaviour: /etc/init.d/myservice has 700 permissions, /etc/init.d has default permissions (``<defaultDirmode>``)

Rationale: ``<defaultFilemode>`` affects only files, not directories, so ``<filemode>`` should affect only files, not directories.

**Comment by rickard-von-essen** [comment]
The current behaviour is consistent with the documentation, see [documentation - filemode](http://www.mojohaus.org/rpm-maven-plugin/map-params.html#filemode).

**Comment by TomyLobo** [comment]
It says "file" everywhere and it makes no mention of directories other than in the reference to defaultDirmode

**Comment by dantran** [comment]
@TomyLobo same behavior on the latest rpm-maven-plugin?

**Comment by bokken** [comment]
I believe that you simply need to set directoryIncluded[1] to false:

<mapping>
    <directory>/etc/init.d</directory>
    <directoryIncluded>false</directoryIncluded>
    <username>root</username>
    <groupname>root</groupname>
    <filemode>700</filemode>
    <sources>
        <source>
            <location>${project.basedir}/src/rpm/data/etc/init.d</location>
        </source>
    </sources>
</mapping>

For reasons I do not completely understand, the behavior of the plugin has
always been to only write out the directory to the generated spec file if
only one mapping contributes to that directory. Setting the
directoryIncluded flag to false forces each of the files to be enumerated
instead.


[1] -
http://www.mojohaus.org/rpm-maven-plugin/map-params.html#directoryIncluded

**Comment by arkhipov** [comment]
I have recently come across this bug/feature. The behaviour makes the `recurseDirectories` option totally useless unless you leave out the `filemode` option and rely on the default permissions.

What, in my opinion, should be done is that an option like `dirmode` should be introduced. Also, it might be a good idea to add an option `preservePermissions` to copy the permissions from existing files. What do you think?

**Comment by bokken** [comment]
The recurseDirectories option is not useless. If you wany the directories
to have different permissions than the files, you need to define a separate
mapping for the directories. The mapping for directories would have no
sources and you would use the recurseDirectories option. The mappings which
contribute files would need to set DirectoryIncluded to false.

**Comment by arkhipov** [comment]
@bokken,
Could you please clarify the idea of using `directoryIncluded`? The only workaround I know is this:

```
<mapping>
  <directory>/var/lib/app</directory>
  <filemode>600</filemode>
  <recurseDirectories>true</recurseDirectories>
  <username>user</username>
  <groupname>group</groupname>
  <sources>
    <source>
      <location>${project.basedir}/src/rpm/data/etc/init.d</location>
    </source>
  </sources>
</mapping>

<mapping>
  <directory>/var/lib/app</directory>
  <filemode>700</filemode>
  <recurseDirectories>true</recurseDirectories>
  <username>user</username>
</mapping>
```

It works but generates loads of warnings `File listed twice`.

**Comment by bokken** [comment]
In your first mapping remove the recurseDirectories entry and set
directoryIncluded[1] to false.

<mapping>
  <directory>/var/lib/app</directory>
  <filemode>600</filemode>
  <directoryIncluded>false</directoryIncluded>
  <username>user</username>
  <groupname>group</groupname>
  <sources>
    <source>
      <location>${project.basedir}/src/rpm/data/etc/init.d</location>
    </source>
  </sources>
</mapping>

<mapping>
  <directory>/var/lib/app</directory>
  <filemode>700</filemode>
  <recurseDirectories>true</recurseDirectories>
  <username>user</username>
</mapping>



[1] -
http://www.mojohaus.org/rpm-maven-plugin/map-params.html#directoryIncluded

**Comment by bokken** [comment]
I am going to close the issue as it appears your workflow is addressed. Please re-open with additional information if you are still having issues.

**Comment by TomyLobo** [comment]
The documentation is a bit confusing. I can't make anything out of it, even now that I know what it does.
