### ISSUE TITLE
rpm signing is broken on CentOS7

### ISSUE THREAD

**Issue by minfrin** [mojohaus/rpm-maven-plugin#83]
When signing on CentOS7, rpmbuild breaks as follows:

[INFO] You must set "%_gpg_name" in your macro file
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.571s
[INFO] Finished at: Thu Aug 03 14:08:20 UTC 2017
[INFO] Final Memory: 9M/27M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.1.5:rpm (default-rpm) on project device-httpd2.4-core: RPM build execution returned: '1' executing '/bin/sh -c cd '/home/minfrin/src/device-zone/platform/el7/device-httpd/device-httpd-2.4-core/trunk/target/rpm/device-httpd2.4-core/SPECS' && 'rpmbuild' '-bb' '--target' 'noarch-redhat-linux' '--buildroot' '/home/minfrin/src/device-zone/platform/el7/device-httpd/device-httpd-2.4-core/trunk/target/rpm/device-httpd2.4-core/buildroot' '--define' '_topdir /home/minfrin/src/device-zone/platform/el7/device-httpd/device-httpd-2.4-core/trunk/target/rpm/device-httpd2.4-core' '--define' '_build_name_fmt %%{ARCH}/%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm' '--define' '_builddir %{_topdir}/BUILD' '--define' '_rpmdir %{_topdir}/RPMS' '--define' '_sourcedir %{_topdir}/SOURCES' '--define' '_specdir %{_topdir}/SPECS' '--define' '_srcrpmdir %{_topdir}/SRPMS' '--define' '_gpg_name platform@device.zone' '--sign' 'device-httpd2.4-core.spec'' -> [Help 1]
[ERROR] 

On CentOS7 the --sign flag is marked as deprecated:

[minfrin@localhost trunk]$ rpmbuild --help | grep sign
  --nosignature                 don't verify package signature(s)
  --sign                        generate GPG signature (deprecated, use
                                command rpmsign instead)

It appears the command is also broken.

To fix this, use rpmsign instead.

**Comment by minfrin** [comment]
PR https://github.com/mojohaus/rpm-maven-plugin/pull/86 fixes the issue.

**Comment by minfrin** [comment]
Quick ping, any news on this one?

**Comment by dantran** [comment]
fixed by RP #86
